apiVersion: v1
kind: Service
metadata:
  name: negotiator-v3-db-service
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    service: negotiator-v3-db-service