version: "3.4"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - traefik.enable=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  negotiator:
    image: bbmrieric/negotiator
    labels:
      - traefik.enable=true
      - traefik.http.routers.negotiator.rule=Host(`${HOST}`) && PathPrefix(`/api`)
      - traefik.http.services.negotiator.loadbalancer.server.port=8080
      - traefik.http.routers.negotiator.entrypoints=web
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/negotiator
      - SPRING_DATASOURCE_USERNAME=negotiator
      - SPRING_DATASOURCE_PASSWORD=negotiator
      - SPRING_DATASOURCE_INITIALIZE=true
      - SPRING_DATASOURCE_DATA=file:/data.sql
      - SPRING_DATASOURCE_INITIALIZATIONMODE=always
      - SPRING_JPA_DEFERDATASOURCEINITIALIZATION=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_USERINFOURI=https://login.bbmri-eric.eu/oidc/userinfo
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=https://login.bbmri-eric.eu/oidc/
      - NEGOTIATOR_FRONTENDURL=https://negotiator-v3.bbmri-eric.eu
      - NEGOTIATOR_AUTHORIZATION_CLAIM=eduperson_entitlement
      - NEGOTIATOR_AUTHORIZATION_ADMINCLAIMVALUE=urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:admins#perun.bbmri-eric.eu
      - NEGOTIATOR_AUTHORIZATION_RESEARCHERCLAIMVALUE=urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:researchers#perun.bbmri-eric.eu
      - NEGOTIATOR_AUTHORIZATION_BIOBANKERCLAIMVALUE=urn:geant:bbmri-eric.eu:group:bbmri:negotiator_v3:biobankers#perun.bbmri-eric.eu
      - NEGOTIATOR_AUTHORIZATION_SUBJECTCLAIM=preferred_username
    depends_on:
      - postgres
  negotiator-frontend:
    container_name: negotiator-frontend
    image: bbmrieric/negotiator-frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.negotiator-frontend.rule=Host(`${HOST}`)
      - traefik.http.services.negotiator-frontend.loadbalancer.server.port=8080
      - traefik.http.routers.negotiator-frontend.entrypoints=web
    env_file:
      - ".env.frontend"
  postgres:
    container_name: negotiator-db
    image: postgres:14
    env_file:
      - ".env.database"
    volumes:
      - negotiator-db-data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
volumes:
  negotiator-db-data:
