version: "3.4"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - --entryPoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/config
    labels:
      - traefik.enable=false
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${PATH_TO_TRAEFIC_DYNAMIC}:/etc/traefik/config/traefik.yaml
      - ${PATH_TO_CERTS}:/etc/certs
  negotiator:
    container_name: negotiator
    image: bbmrieric/negotiator:${BACKEND_TAG:-latest}
    labels:
      - traefik.enable=true
      - traefik.http.routers.negotiator.tls=true
      - traefik.http.routers.negotiator.rule=Host(`${HOST}`) && PathPrefix(`/api`)
      - traefik.http.services.negotiator.loadbalancer.server.port=8080
      - traefik.http.routers.negotiator.entrypoints=websecure
    env_file:
      - ".env.backend"
    depends_on:
      - postgres
  negotiator-frontend:
    container_name: negotiator-frontend
    image: bbmrieric/negotiator-frontend:${FRONTEND_TAG:-latest}
    labels:
      - traefik.enable=true
      - traefik.http.routers.negotiator-frontend.tls=true
      - traefik.http.routers.negotiator-frontend.rule=Host(`${HOST}`)
      - traefik.http.services.negotiator-frontend.loadbalancer.server.port=8080
      - traefik.http.routers.negotiator-frontend.entrypoints=websecure
    env_file:
      - ".env.frontend"
  postgres:
    container_name: negotiator-db
    image: postgres:14
    env_file:
      - ".env.database"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - negotiator-db-data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
volumes:
  negotiator-db-data:
